language: ruby
before_install:
  # Travis bundler versions are quite out of date and can cause install errors
  # see: https://github.com/rubygems/rubygems/issues/1419
  - gem update bundler
rvm:
- 1.9.3
- 2.0.0
- 2.1.7
- 2.2.3
- 2.3.0
- 2.4.0
- 2.5.0
- 2.6.0
env:
  global:
    secure: MBTxmpWCjrsNKPlOoFwJUMHze3GPMz8YCXQFQG3zJBh3WGNQnz4z91ra/1P/DClyVCxHGSFCOswxCNe4kJ2zAnPyQLqGSinXy9uDpqZQUEdaRoQbPnh4/bguZNSJ429gtTpMdDSNOgQ+Hra2EFnWwHA+rLF6ImksMsu3XGKGxGE=
